### ISSUE TITLE
META ISSUE: Add modules and functions to CoreMS needed for lipidomics workflow

### ISSUE THREAD

**Issue by kheal** [microbiomedata/metaMS#27]
- [x] Add MassSpectra and LCMSBase classes to lcms_dev on CoreMS
- [x] Modify mass_spectra/input modules to lcms_dev on CoreMS
- [x] #37
- [x] #38 
- [x] #46
- [x] #40
- [x] #58
- [x] #39
- [x] #51
- [x] #41
- [x] #52
- [x] #53
- [x] #54
- [x] Release new version of CoreMS

**Comment by kheal** [comment]
Related to MRs in CoreMS on github
